"""Jupyter notebook generation utilities."""

import json
from pathlib import Path

import nbformat


def cells_to_notebook(cells: list[dict]) -> nbformat.NotebookNode:
    """Convert a list of cell dicts to a Jupyter notebook.

    Each cell dict should have:
      - cell_type: "markdown" or "code"
      - source: the cell content string
    """
    nb = nbformat.v4.new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    for cell_data in cells:
        cell_type = cell_data.get("cell_type", "code")
        source = cell_data.get("source", "")

        if cell_type == "markdown":
            cell = nbformat.v4.new_markdown_cell(source)
        else:
            cell = nbformat.v4.new_code_cell(source)

        nb.cells.append(cell)

    return nb


def save_notebook(nb: nbformat.NotebookNode, path: str | Path) -> None:
    """Save a notebook to disk."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        nbformat.write(nb, f)


def create_course_readme_notebook(
    course_title: str, course_description: str, modules: list[dict]
) -> nbformat.NotebookNode:
    """Create an overview notebook that serves as the course README."""
    cells = [
        {
            "cell_type": "markdown",
            "source": f"# {course_title}\n\n{course_description}",
        },
        {
            "cell_type": "markdown",
            "source": "## Course Structure\n\n"
            + "\n".join(
                f"**Module {m['module_index']}:** [{m['title']}]"
                f"(./{_slugify(m['module_index'], m['title'])}.ipynb)\n"
                f"> {m['description']}\n"
                for m in modules
            ),
        },
        {
            "cell_type": "markdown",
            "source": "## How to Use This Course\n\n"
            "1. Work through modules in order — each builds on the previous\n"
            "2. For each exercise, read the docstring and implement the `TODO` section\n"
            "3. Run the test cell immediately after to validate your implementation\n"
            "4. Answer the **Inline Questions** in your own words before moving on\n"
            "5. Don't peek at solutions — the struggle is where learning happens\n\n"
            "---\n*Generated by Scaffoldly*",
        },
    ]
    return cells_to_notebook(cells)


def _slugify(index: int, title: str) -> str:
    """Create a filesystem-safe slug from module index and title."""
    slug = title.lower()
    slug = "".join(c if c.isalnum() or c == " " else "" for c in slug)
    slug = slug.strip().replace(" ", "_")
    # Truncate long slugs
    slug = slug[:50].rstrip("_")
    return f"{index:02d}_{slug}"
